### ISSUE TITLE
Repository name mismatch repository target

### ISSUE THREAD

**Issue by mhdolatabadi** [komakestan/fundamentals-of-programming#1]
better name for it is "fundamentals of programming".

**Comment by machitgarha** [comment]
Thanks. Changed.

P.S.: You could post issues and other stuff in Persian, as the main language of Komakestan is Persian basically. And it is highly recommended, also.

**Comment by mhdolatabadi** [comment]
If you think writing persian is better choice, then you should change the repo name to mabani-barname-sazi

**Comment by machitgarha** [comment]
@mhdolatabadi, sorry, but I hate finglish. :) I think English for repo names is just more informative (even when the content is not English) and more readable. [Vazir-font](https://github.com/rastikerdar/vazir-font) is an example.

**Comment by mhdolatabadi** [comment]
> @mhdolatabadi, sorry, but I hate finglish. :) I think English for repo names is just more informative (even when the content is not English) and more readable. [Vazir-font](https://github.com/rastikerdar/vazir-font) is an example.

Do you hate fingilish? but taking a look on your repositories says something else

**Comment by machitgarha** [comment]
@mhdolatabadi, 😄, they are just plain names, like Amin. You write it exactly the same way as you write in Persian. I wanted those names to be Persian, and that's why. But, course names are a different story, and you don't name a course; they are just there.

**Comment by mhdolatabadi** [comment]
Thanks. It was usefull information!

**Comment by mhdolatabadi** [comment]
@machitgarha OK. got it!
