### ISSUE TITLE
ایجاد بی انگیزگی در دانشجویان ورودی غیر حضوری

### ISSUE THREAD

**Issue by muhmah-motahari** [komakestan/fundamentals-of-programming#2]
<div dir="rtl">
هنگامی که ویروس کرونا همه گیری شد دانشگاه ها هم نیز مجبور به غیر حضوری کردن آموزش دانشجویان شدند.
وقتی هم که دانش اموزی با تلاش زیادی که در آزمون کنکور داشته با کلی آرزو وارد دانشگاه میشه که خب متاسفانه باید از توی خونه وارد دانشگاه میشد
که این مسئله مشکلات زیادی را ایجاد میکرد
مهمترین مشکلات رو میشه به عدم ارتباط حضوری با بقیه دانشجوها دانست
که بسیاری از انگیزه دانشجو ها در همین فقدان ارتباط از بین میره

برای مثال روند یک دانشجو ورودی را میگم:
دانش اموز با کلی ذوق وارد سایت سنجش میشه و متوجه میشه در رشته کامپیوتر دانشگاه بوعلی سینا قبول شده
حالا پیگیر کاراش میشه که مدارک را بفرسته و پذیرش بشه
سپس اولین درس مهمی که با اون مواجه میشه مبانی برنامه نویسی هستش
اول تلاشش رو میکنه که نمره خوبی بگیره ولی وقتی با مشکلات متعدد روبرو میشه با سختگیری اساتید
در ضمن این دانشجو را باید در نظر بگیرید که هیچ پیش زمینه ای از برنامه نویسی نداره

حالا با کلی تمرین و یه سری نمرات خیلی بد روبرو شده
و با توجه به اینکه درس مبانی مطالب زیادی داره و از هیچکدوم نمیشه کم کرد بدلیل اهمیتشون
و همه این ها دست به دست هم میدن که دانشجو دچار بی انگیزگی میشه
چونکه کسی هم نیست که اونو خوب راهنمایی کنه و انگیزه بهش بده تا بتونه این سختی هارو راحت تر تحمل کنه
البته که دستیاران استاد هستند که اگر دانشجو بخواهد با انها مشکلاتشون را مطرح کنند ولی خب رابطه دستیار با دانشجو اصلا بگونه ای نیست که دانشجو بتونه راحت باهاش باشه و بازم نمیتونه خیلی خوب بهش انگیزه بده.
</div>

**Comment by machitgarha** [comment]
<div dir="rtl">

خیلی هم عالی؛ و ممنون.

البته فکر کنم خیلی مشکل‌های زیادی توی این مواردی که گفته شد، گنجونده شده باشه. اما، ممنون از مطرح کردنش.

مهم‌ترین موضوع برای رفع این مشکل‌ها، راهکارها هست. اگر راهکاری برای هر یک از این مشکلات هست، مشتاق اون‌ها هم هستیم و می‌تونیم اون‌ها رو هم مطرح کنیم و درباره‌شون صحبت کنیم (البته باید موضوعات جزیی‌تر از این بشن تا بتونیم هر کدوم رو در یک‌جا دنبال کنیم).

یه موضوعی هم که هست، اینه که متاسفانه هنوز زیرساخت برای کمکستان به صورت خوب فراهم نیست؛ چه برسه به این مخزن که به تازگی ایجاد شده. شاید بهتر باشه که اول یه فکری به حال این مشکل بکنیم و پایه‌های کمکستان (ساختاری و محتوایی) رو بریزیم، تا بعد بتونیم نتیجه‌ی کارها و صحبت‌ها رو به صورت مستند در بیاریم. البته، متاسفانه یا خوشبختانه، تمرکز من به شخصه روی درس برنامه‌نویسی پیشرفته هست؛ اما خب خیلی از موضوعات، مخصوصا این مشکل، می‌تونه بین این دو درس مشترک باشه؛ و شاید حتی لازم باشه به این درس بیش‌تر پرداخته بشه.

به هر حال، من سعی‌ام رو می‌کنم یه نگاه دقیق‌تری در آینده‌ای نزدیک روی این موضوع داشته باشم؛ بلکه بتونیم حلش کنیم. ولی اگه فکر می‌کنین دیر می‌شه، مشارکت یعنی همین؛ بسم‌الله، من منتظر مستندها و محتواهای همگی هستم (چون دیگه ترم هم داره شروع می‌شه). فقط باید یه حرکت جهشی داشته باشیم در این زمینه.

برای زیرساخت این‌که چطوری مطلب بنویسیم هم، می‌تونین به [این](https://github.com/komakestan/advanced-programming/blob/assignments/docs/fa/assignments/making.md) هم یه نگاه بکنین.

</div>

**Comment by muhmah-motahari** [comment]
<div dir="rtl">
**ایجاد تیم پشتیبانی برای دانشجویان ورودی**

توضیح مشکل:
	بدلیل غیر حضوری بودن ورود دانشجویان به دانشگاه ، ارتباط دانشجو بسیار محدود تر هستش و اگرم خود دانشجو ارتباط با کسی برقرار نکنه هیچکس پیگیر او نمیشود
	همین عدم ارتباط دانشجو باعث میشه که با تمامی مشکلاتی که روبرو میشه فقط خودش به تنهایی اونهارو حل بکنه ، که اینطوری به احتمال زیاد با توجه به مشکلات زیاد و سختگیری هایی که 	وجود داره دانشجو نتیجتا دچار بی انگیزگی میشه.

راه حل:
	ایجاد تیم پشتیبانی برای روحیه دادن به دانشجویان
	
توضیح:
	بودن یک تیم پشتیبان (نه دستیار استاد) که هدف اصلی انها روحیه دادن به دانشجویان ورودی باشه میتونه تاثیر بسزایی در رفع این مشکل داشته باشه
	بصورتی که برای هر فرد در تیم پشتیبان ۳-۴ نفر از دانشجویان ورودی منسوب بشن و وظیفه فرد پشتیبان این باشه که با دانشجویانش ارتباط بگیره و مسائل را براشون قبل از برخورد دانشجو با اونها توضیح بده و پیگیر اوضاع دانشجو باشه.
	برای مثال هر هفته پیگیر شود که دانشجو چند قسمت از فیلم های اموزشی استاد را مشاهده کرده و وضعیتش چطور است؛ اینکه چند روز قبل از هر امتحان پیگیر اوضاع درسیش شود.
	
نکته:
	تیم پشتیبان جدای از تیم دستیاران اموزشی میباشد و پشتیبانان دخالتی در امر اموزش ندارند؛ بدلیل اینکه اعضای تیم پشتیبانی نیازی به سطح بالای دانش و تخصص ندارند، میشود تعداد اعضای پشتیبان را زیاد کرد که البته اگر فردی هم با تخصص در میان پشتیبانان بود به تشخیص استاد میتواند عضو تیم دستیاران استاد هم باشد.
	
فواید:
	* احساس اهمیت دانشتن و بالا بردن ارزش دانشجو برای دانشگاه
	* رها نشدن دانشجو در ترم اول (غیر حضوری)
	* افزایش بازدهی خروجی دانشجویان
	
معایب:
	* نیاز به تعداد زیادی دانشجو برای ساخت تیم پشتیبان
	* درصورتی که عضوی از تیم پشتیبان نتواند کارش را بدرستی انجام دهد ممکن است برای دانشجویانش مضر باشد
</div>

**Comment by machitgarha** [comment]
<div dir="rtl">

ممنونم که این وقتو گذاشتی! این خیلی عالیه. دقیقا به چنین چیزهایی نیاز داریم.

اگر می‌خوای، می‌تونی یه درخواست ادغام (پی‌آر؟) بزنی که اینو توی یه فایلی ثبت کرده باشه؛ و با کمال میل پذیرفته می‌شه. البته درسته که هنوز شاکله‌ی خیلی کاملی نداره این مخزن؛ اما خب فعلا هر کجا که باشه، خوبه.

اگر هم، یه درخواستی باشه که مثلا این زیرساخت‌ها رو، نه تا حد عالی، ولی مثل همین‌که یه پرونده‌ی بخوانید (ریدمی 😄) داشته باشه و ارجاعات مختلف و اینا رو توش جا داده باشه، واقعا عالی می‌شه و این هم با کمال میل پذیرفته می‌شه. برای این کار هم، می‌شه از مخزن [برنامه‌نویسی پیشرفته](https://github.com/komakestan/advanced-programming/tree/develop#readme) استفاده کرد و ایده یا حتی رونوشت گرفت.

بازم ممنون.

</div>

**Comment by muhmah-motahari** [comment]
<div dir="rtl">
بسیار عالی</br>
فقط بدلیل اینکه مخزن خالی هستش اجازه ساخت شاخه (فورک) نمیدهد</br>
فکر میکنم اول باید یک فایلی را ایجاد کنید تا بتونم تغییراتی بدم و درخواست ادغام بدم.
</div>

**Comment by machitgarha** [comment]
<div dir="rtl">

درست شد.

</div>
